from app.repository.flight.structure.filter_groups.airlines import FilterAirlinesDTO
from app.repository.flight.structure.filter_groups.airports import FilterAirportsDTO
from app.repository.flight.structure.filter_groups.alliance import FilterAllianceDTO
from app.repository.flight.structure.filter_groups.baditin import FilterBaditinDTO
from app.repository.flight.structure.filter_groups.bfc import FilterBfcDTO
from app.repository.flight.structure.filter_groups.cabin import FilterCabinDTO
from app.repository.flight.structure.filter_groups.cfc import FilterCfcDTO
from app.repository.flight.structure.filter_groups.currency import FilterCurrencyDTO
from app.repository.flight.structure.filter_groups.eqmodel import FilterEqModelDTO
from app.repository.flight.structure.filter_groups.equipment import FilterEquipmentDTO
from app.repository.flight.structure.filter_groups.hidebasic import FilterHideBasicDTO
from app.repository.flight.structure.filter_groups.landing import FilterLandingDTO
from app.repository.flight.structure.filter_groups.layoverair import FilterLayoverAirDTO
from app.repository.flight.structure.filter_groups.layoverdur import FilterLayoverDurDTO
from app.repository.flight.structure.filter_groups.legdur import FilterLegDurDTO
from app.repository.flight.structure.filter_groups.pfc import FilterPfcDTO
from app.repository.flight.structure.filter_groups.price import FilterPriceDTO
from app.repository.flight.structure.filter_groups.providers import FilterProvidersDTO
from app.repository.flight.structure.filter_groups.redeye import FilterRedeyeDTO
from app.repository.flight.structure.filter_groups.sameair import FilterSameAirDTO
from app.repository.flight.structure.filter_groups.specificleg import FilterSpecificLegDTO
from app.repository.flight.structure.filter_groups.split import FilterSplitDTO
from app.repository.flight.structure.filter_groups.stops import FilterStopsDTO
from app.repository.flight.structure.filter_groups.takeoff import FilterTakeOffDTO
from app.repository.flight.structure.filter_groups.wifi import FilterWifiDTO
