# models/booking.py
"""
Booking domain — the core transactional entity of the platform.

Architecture: Joined Table Inheritance (JTI)
--------------------------------------------
`Booking` is the polymorphic parent.  Every booking — regardless of service
type — gets one row in `bookings`.  Type-specific details live in child
tables joined by a 1:1 FK on the same PK.

    bookings
      └── flight_bookings   (FlightBooking)
            └── flight_segments  (FlightSegment — multi-leg support)
      └── hotel_bookings    (HotelBooking)
      └── car_bookings      (CarBooking)
      └── package_bookings  (PackageBooking)

Why JTI over Single-Table Inheritance?
  - Avoids a single bloated table with 30+ nullable columns.
  - Each service type can have NOT NULL constraints on its own columns.
  - SQL queries on a single type skip irrelevant joins.

Why NOT Concrete Table Inheritance?
  - We want a single `bookings` table to query across all service types
    (e.g. "show all bookings for client X" without UNION).

BookingPassenger
----------------
For group / family bookings, multiple passengers share one Booking row.
The first (or flagged) passenger is the lead traveller.
"""

from decimal import Decimal
from typing import TYPE_CHECKING

from sqlalchemy import (
    Boolean, DateTime, Enum, 
    ForeignKey, Numeric,String, Text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import AuditMixin, db
from app.enums import BookingStatus, BookingServiceType

if TYPE_CHECKING:
    from .client import Client
    from .fee import ServiceFeeSnapshot
    from .payment import Payment

class Booking(db.Model, AuditMixin):
    """
    Polymorphic parent for all booking types.

    Key fields
    ----------
    reference_number  — human-readable identifier (e.g. TG-2024-001234).
                        Generated by the service layer before insert.
    service_type      — discriminator for the JTI child.
    status            — full booking lifecycle.
    total_service_fee — the agency fee charged (NOT the ticket price).
                        Ticket prices are tracked separately in child tables.
    is_emergency      — flags last-minute bookings (+$25 surcharge applies).
    is_group          — flags group bookings (different fee schedule).
    agent_notes       — internal notes from the booking agent.
    client_notes      — special requests from the client.
    """

    __tablename__ = "bookings"
    __mapper_args__ = {
        "polymorphic_on": "service_type",
        "polymorphic_identity": None,
    }

    reference_number: Mapped[str] = mapped_column(
        String(30), unique=True, nullable=False, index=True,
        doc='Human-readable booking ID, e.g. "TG-2024-001234".',
    )
    service_type: Mapped[BookingServiceType] = mapped_column(
        Enum(BookingServiceType, name="booking_service_type_enum"),
        nullable=False,
        index=True,
    )
    status: Mapped[BookingStatus] = mapped_column(
        Enum(BookingStatus, name="booking_status_enum"),
        nullable=False,
        default=BookingStatus.PENDING_PAYMENT,
        index=True,
    )

    client_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("clients.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    total_service_fee_usd: Mapped[Decimal] = mapped_column(
        Numeric(10, 2), nullable=False,
        doc="Agency service fee billed to the client (not the ticket cost).",
    )
    ticket_cost_usd: Mapped[Decimal | None] = mapped_column(
        Numeric(10, 2), nullable=True,
        doc="Underlying ticket / hotel / car cost (informational, for margin tracking).",
    )
    currency: Mapped[str] = mapped_column(
        String(3), nullable=False, default="USD",
        doc="ISO 4217 code. Extend to multi-currency when needed.",
    )
    discount_amount_usd: Mapped[Decimal] = mapped_column(
        Numeric(10, 2), nullable=False, default=Decimal("0.00"),
        doc="Loyalty / referral discount applied.",
    )

    # Flags
    is_emergency: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False,
        doc="Last-minute booking; +$25 surcharge applies.",
    )
    is_group: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False,
        doc="Group booking (min 5 pax); group fee schedule applies.",
    )

    # Notes
    agent_notes: Mapped[str | None] = mapped_column(
        Text, nullable=True, doc="Internal notes from the booking agent."
    )
    client_notes: Mapped[str | None] = mapped_column(
        Text, nullable=True, doc="Special requests submitted by the client."
    )

    # Timestamps beyond AuditMixin
    confirmed_at: Mapped[DateTime | None] = mapped_column(
        DateTime(timezone=True), nullable=True,
        doc="When status moved to CONFIRMED.",
    )
    cancelled_at: Mapped[DateTime | None] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    completed_at: Mapped[DateTime | None] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )

    # Relationships
    client: Mapped["Client"] = relationship("Client", back_populates="bookings")
    passengers: Mapped[list["BookingPassenger"]] = relationship(
        "BookingPassenger",
        back_populates="booking",
        cascade="all, delete-orphan",
        lazy="selectin",
    )
    payments: Mapped[list["Payment"]] = relationship(
        "Payment",
        back_populates="booking",
        cascade="all, delete-orphan",
        lazy="dynamic",
    )
    fee_snapshot: Mapped["ServiceFeeSnapshot | None"] = relationship(
        "ServiceFeeSnapshot",
        back_populates="booking",
        uselist=False,
        lazy="joined",
    )

    @property
    def amount_due(self) -> Decimal:
        """Outstanding balance = fee − discount − payments received."""
        paid = sum(
            p.amount_usd for p in self.payments
            if p.status.value in ("confirmed", "partially_refunded")
        )
        return self.total_service_fee_usd - self.discount_amount_usd - paid

    def __repr__(self) -> str:
        return f"<Booking {self.reference_number} [{self.service_type.value}/{self.status.value}]>"
